# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    taro_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

taro_arm_controller:
  ros__parameters:
    joints:
      - mobile_base_arm_joint
      - base_forearm_joint
      - forearm_hand_joint
      - hand_hand_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
hand_controller:
  ros__parameters:
    joint: eef_eef_left_joint