<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />
    <xacro:include filename="arm.xacro" />
    <xacro:include filename="arm_gazebo.xacro" />
    <xacro:include filename="camera.xacro" />

    <joint name = "mobile_base_arm_joint" type = "revolute">
        <parent link = "base_link"/>
        <child link = "arm_base_link"/>
        <origin xyz = "${base_length/4} 0 ${base_height}" rpy= "0 0 0"/>
        <axis xyz = "0 0 1"/>
        <limit lower = "${-pi}" upper = "${pi}" effort = "100" velocity = "100"/>
        <dynamics friction = "0.3" damping = "0.3"/>
    </joint>

</robot>